### ISSUE TITLE
replace Travis CI and AppVeyor with GitHub actions

### ISSUE THREAD

**Issue by dirk-thomas** [colcon/colcon-core#420]
While #414 takes a stab at this already the goal here is to switch CI not only for this repository but for all extensions too. To avoid duplicating configuration and logic it is likely useful to create a custom GitHub action which can then be used across multiple repos with minimal customization.

Also the current Travis CI integration uses `travis-ci.org` which is deprecated already.Instead of migrating to `travis-ci.com` using GitHub actions seems like the more future proof solution.

**Comment by tylerjw** [comment]
As you go through this I'm curious to hear what you found that was good (and bad) about GitHub actions.  We are also currently on travis for MoveIt and some of their latest changes to their service has gotten us looking at other options.  After comparing them I'm currently pursuing CircleCI for our uses but GitHub Actions is the other one we are still somewhat considering.

**Comment by cottsay** [comment]
After researching how GitHub Actions work, I've arrived at the following approach:
* A central GitHub [Composite Action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) hosted at https://github.com/colcon/ci
* A central workflow template hosted at https://github.com/colcon/.github/blob/main/workflow-templates/ci.yaml
* Individual workflow manifestations which look like this: colcon/colcon-cmake#100

It's worth calling out a couple of things:
1. There is no mechanism to centrally manage the build matrix among repositories in an organization. A custom action (composite or otherwise) cannot control this - it must be part of the workflow. The central workflow template is the best I could do, but adjusting the template doesn't adjust the already existing workflows.
2. A composite action can only run shell commands and can't call other actions, so the steps for checkout and python setup can't be moved into the custom action at this time.
3. The custom action does the following:
   a. Set up a virtual environment and install pytest
   b. Install the test dependencies for the candidate package
   c. Upgrade any colcon dependencies that were installed to install from Git directly, as is the current pattern

Next steps are to review #445 and colcon/colcon-cmake#100, as well as the new [ci](https://github.com/colcon/ci) and [.github](https://github.com/colcon/.github) repositories I've created to prototype this system.

Once that's done, I'll open PRs against other colcon repositories to transition everything to GitHub Actions.

**Comment by cottsay** [comment]
Here's the progress:
- [x] colcon/colcon-core#445
- [ ] colcon/colcon-cmake#100
- [ ] colcon/colcon-output#40
- [ ] colcon/colcon-ros#131
- [ ] colcon/colcon-parallel-executor#25

...more to come.
